framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\SendBorrowingConfirmationEmail: async
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
